"""
email_service.py — SMTP / Gmail Email Service
OrchestrAI Autonomous Multi-Agent System

Handles:
  - Composing rich HTML + plain-text internship report emails
  - Sending via SMTP (Gmail App Password / any SMTP relay)
"""

import os
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("CareerAgent.EmailService")

EMAIL_USER: str     = os.getenv("EMAIL_USER", "")
EMAIL_PASS: str     = os.getenv("EMAIL_PASS", "")
EMAIL_RECEIVER: str = os.getenv("EMAIL_RECEIVER", "")
SMTP_HOST: str      = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT: int      = int(os.getenv("SMTP_PORT", "587"))


# ──────────────────────────────────────────────
# HTML Template
# ──────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Daily AI &amp; Data Science Internship Report</title>
<style>
  body {{
    font-family: 'Segoe UI', Arial, sans-serif;
    background: #f4f6fb;
    color: #222;
    margin: 0;
    padding: 0;
  }}
  .container {{
    max-width: 860px;
    margin: 32px auto;
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 4px 24px rgba(0,0,0,0.09);
    overflow: hidden;
  }}
  .header {{
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    color: #e0e0ff;
    padding: 32px 36px 24px;
  }}
  .header h1 {{
    margin: 0 0 6px;
    font-size: 22px;
    letter-spacing: 0.5px;
  }}
  .header p {{
    margin: 0;
    font-size: 13px;
    opacity: 0.75;
  }}
  .stats {{
    display: flex;
    gap: 20px;
    padding: 18px 36px;
    background: #f0f4ff;
    border-bottom: 1px solid #dde3f0;
  }}
  .stat {{
    background: #fff;
    border-radius: 8px;
    padding: 10px 20px;
    text-align: center;
    box-shadow: 0 1px 6px rgba(0,0,0,0.07);
    min-width: 80px;
  }}
  .stat-num {{ font-size: 22px; font-weight: 700; color: #0f3460; }}
  .stat-lbl {{ font-size: 11px; color: #666; margin-top: 2px; }}
  table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }}
  thead tr {{
    background: #0f3460;
    color: #fff;
    text-align: left;
  }}
  thead th {{
    padding: 12px 14px;
    font-weight: 600;
    letter-spacing: 0.3px;
  }}
  tbody tr:nth-child(even) {{ background: #f7f9ff; }}
  tbody tr:hover {{ background: #e8eeff; transition: background 0.15s; }}
  td {{
    padding: 11px 14px;
    vertical-align: top;
    border-bottom: 1px solid #eaedf5;
    line-height: 1.5;
  }}
  .badge {{
    display: inline-block;
    background: #e6eaff;
    color: #0f3460;
    border-radius: 12px;
    padding: 2px 8px;
    font-size: 11px;
    margin: 2px 2px 2px 0;
    white-space: nowrap;
  }}
  .apply-btn {{
    display: inline-block;
    background: #0f3460;
    color: #fff !important;
    padding: 5px 14px;
    border-radius: 20px;
    text-decoration: none;
    font-size: 12px;
    font-weight: 600;
  }}
  .apply-btn:hover {{ background: #1a56db; }}
  .footer {{
    text-align: center;
    padding: 18px;
    font-size: 11.5px;
    color: #999;
    background: #f4f6fb;
  }}
  .source-tag {{
    font-size: 10.5px;
    color: #888;
    display: block;
    margin-top: 2px;
  }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>🤖 Daily AI &amp; Data Science Internship Report</h1>
    <p>Generated by OrchestrAI Career Agent · {date_str} · {total} relevant roles found</p>
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-num">{total}</div>
      <div class="stat-lbl">Total Jobs</div>
    </div>
    <div class="stat">
      <div class="stat-num">{remote_count}</div>
      <div class="stat-lbl">Remote</div>
    </div>
    <div class="stat">
      <div class="stat-num">{sources_count}</div>
      <div class="stat-lbl">Sources</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Company</th>
        <th>Role</th>
        <th>Location</th>
        <th>Role Keywords</th>
        <th>Technical Skills</th>
        <th>Apply</th>
      </tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>

  <div class="footer">
    OrchestrAI Career Agent · Auto-generated · Do not reply to this email<br/>
    Report time: {date_str} IST
  </div>
</div>
</body>
</html>
"""

_ROW_TEMPLATE = """\
      <tr>
        <td>{idx}</td>
        <td><strong>{company}</strong><span class="source-tag">via {source}</span></td>
        <td>{role}</td>
        <td>{location}</td>
        <td>{keywords_html}</td>
        <td>{skills_html}</td>
        <td><a class="apply-btn" href="{apply_link}" target="_blank">Apply →</a></td>
      </tr>"""

_PLAIN_TEMPLATE = """\
Daily AI & Data Science Internship Report
Generated: {date_str}
Total roles: {total}
========================================

{plain_rows}

--
OrchestrAI Career Agent | Auto-generated
"""


# ──────────────────────────────────────────────
# Formatting helpers
# ──────────────────────────────────────────────

def _badges(items: list[str]) -> str:
    """Wrap each item in a small coloured badge span."""
    return "".join(f'<span class="badge">{item.strip()}</span>' for item in items if item.strip())


def format_jobs_email(jobs: list[dict]) -> tuple[str, str]:
    """
    Build HTML and plain-text email bodies from the list of job dicts.
    Returns (html_body, plain_body).
    """
    date_str = datetime.now().strftime("%d %b %Y, %I:%M %p")
    total = len(jobs)
    remote_count = sum(1 for j in jobs if "remote" in j.get("location", "").lower())
    sources = {j.get("source", "unknown") for j in jobs}

    html_rows = []
    plain_rows = []

    for idx, job in enumerate(jobs, start=1):
        company     = job.get("company", "N/A")
        role        = job.get("role", "N/A")
        location    = job.get("location", "N/A")
        apply_link  = job.get("apply_link", "#")
        keywords    = job.get("role_keywords", [])
        skills      = job.get("technical_skills", [])
        source      = job.get("source", "unknown")

        html_rows.append(_ROW_TEMPLATE.format(
            idx=idx,
            company=company,
            source=source,
            role=role,
            location=location,
            keywords_html=_badges(keywords) if keywords else "<em>—</em>",
            skills_html=_badges(skills) if skills else "<em>—</em>",
            apply_link=apply_link,
        ))

        plain_rows.append(
            f"{idx}. {company} — {role}\n"
            f"   Location : {location}\n"
            f"   Source   : {source}\n"
            f"   Keywords : {', '.join(keywords)}\n"
            f"   Skills   : {', '.join(skills)}\n"
            f"   Apply    : {apply_link}\n"
        )

    html_body = _HTML_TEMPLATE.format(
        date_str=date_str,
        total=total,
        remote_count=remote_count,
        sources_count=len(sources),
        rows="\n".join(html_rows),
    )
    plain_body = _PLAIN_TEMPLATE.format(
        date_str=date_str,
        total=total,
        plain_rows="\n".join(plain_rows),
    )
    return html_body, plain_body


# ──────────────────────────────────────────────
# Send
# ──────────────────────────────────────────────

def send_email(
    jobs: list[dict],
    subject: str = "Daily AI & Data Science Internship Report",
    receiver: Optional[str] = None,
) -> bool:
    """
    Compose and send the internship report email via SMTP.
    Returns True on success, False on failure.
    """
    to_addr = receiver or EMAIL_RECEIVER

    if not all([EMAIL_USER, EMAIL_PASS, to_addr]):
        raise EnvironmentError(
            "EMAIL_USER, EMAIL_PASS, and EMAIL_RECEIVER must be set in environment."
        )

    html_body, plain_body = format_jobs_email(jobs)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_USER
    msg["To"]      = to_addr

    msg.attach(MIMEText(plain_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(EMAIL_USER, EMAIL_PASS)
            server.sendmail(EMAIL_USER, to_addr, msg.as_string())
        logger.info("EmailService: Email sent to %s (%d jobs).", to_addr, len(jobs))
        return True
    except smtplib.SMTPAuthenticationError as exc:
        logger.error("EmailService: SMTP authentication failed — %s", exc)
        raise
    except Exception as exc:
        logger.error("EmailService: Failed to send email — %s", exc)
        raise
